"""Sphinx configuration for https://spiflash.readthedocs.io/.

The vendor and chip pages, and the numbers the home page quotes, come from
the installed spiflash package's data through _ext/spiflash_pages.py, so the
site always matches the release it is built from. The API reference is
generated by autosummary from the package and from tools/spiflash_extract.
"""

from __future__ import annotations

import sys
from pathlib import Path

import spiflash

# The site's own extension, and the extraction tools the API reference covers.
sys.path.insert(0, str(Path(__file__).resolve().parent / "_ext"))
sys.path.insert(0, str(Path(__file__).resolve().parent.parent / "tools"))

project = "spiflash"
author = "Tim Ansell"
project_copyright = "2026, Tim Ansell"
release = spiflash.__version__
version = release

extensions = [
    "myst_parser",
    "sphinx_design",
    "sphinx_copybutton",
    "sphinx.ext.autodoc",
    "sphinx.ext.autosummary",
    "sphinx.ext.intersphinx",
    "sphinx.ext.viewcode",
    "sphinxcontrib.wavedrom",
    "spiflash_pages",
]

# Render the opcode pages' timing diagrams to SVG at build time, so the site
# needs no JavaScript to show them.
render_using_wavedrompy = True
wavedrom_html_jsinline = False

source_suffix = {".md": "markdown", ".rst": "restructuredtext"}
exclude_patterns = ["_build", "_generated", "superpowers", "Thumbs.db", ".DS_Store"]
templates_path = ["_templates"]

myst_enable_extensions = ["colon_fence", "deflist", "substitution", "attrs_inline"]
myst_heading_anchors = 3

# Every module, every member: the reference is generated, not curated.
autosummary_generate = True
autosummary_ignore_module_all = True
autodoc_default_options = {
    "members": True,
    "undoc-members": True,
    "show-inheritance": True,
    "member-order": "bysource",
    # Each module documents what it defines: spiflash re-exports Flash and
    # friends, which spiflash.model documents.
    "ignore-module-all": True,
}
autodoc_typehints = "description"
intersphinx_mapping = {"python": ("https://docs.python.org/3", None)}

html_theme = "furo"
html_title = "spiflash"
html_static_path = ["_static"]
html_css_files = ["spiflash.css"]
html_js_files = ["tables.js"]
html_logo = "_static/logo.svg"
html_favicon = "_static/logo.svg"
html_theme_options = {
    "source_repository": "https://github.com/mithro/spiflash/",
    "source_branch": "main",
    "source_directory": "docs/",
    "light_css_variables": {
        "color-brand-primary": "#0f766e",
        "color-brand-content": "#0f766e",
        "font-stack--monospace": "'JetBrains Mono', 'SFMono-Regular', Menlo, Consolas, monospace",
    },
    "dark_css_variables": {
        "color-brand-primary": "#2dd4bf",
        "color-brand-content": "#5eead4",
    },
}
# Generated pages carry no "edit this page" source to edit.
html_show_sourcelink = False
